// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH4h9Pxp8sp4jVhF_wcjYAFKugJI7Pod0',
    appId: '1:432021705260:web:003819a9a695ed0d4ff789',
    messagingSenderId: '432021705260',
    projectId: 'sigin-c8c28',
    authDomain: 'sigin-c8c28.firebaseapp.com',
    storageBucket: 'sigin-c8c28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt7YlhyTOEuvwPUATmXBdr9I3UtJlc--o',
    appId: '1:432021705260:android:595b2b075f4ad64c4ff789',
    messagingSenderId: '432021705260',
    projectId: 'sigin-c8c28',
    storageBucket: 'sigin-c8c28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGx6MmrUllY7DaQx6emPbjumVCzxuMp64',
    appId: '1:432021705260:ios:28f92a3938f4f7c24ff789',
    messagingSenderId: '432021705260',
    projectId: 'sigin-c8c28',
    storageBucket: 'sigin-c8c28.appspot.com',
    iosBundleId: 'com.example.signup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGx6MmrUllY7DaQx6emPbjumVCzxuMp64',
    appId: '1:432021705260:ios:28f92a3938f4f7c24ff789',
    messagingSenderId: '432021705260',
    projectId: 'sigin-c8c28',
    storageBucket: 'sigin-c8c28.appspot.com',
    iosBundleId: 'com.example.signup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH4h9Pxp8sp4jVhF_wcjYAFKugJI7Pod0',
    appId: '1:432021705260:web:d91286de7fd25f6c4ff789',
    messagingSenderId: '432021705260',
    projectId: 'sigin-c8c28',
    authDomain: 'sigin-c8c28.firebaseapp.com',
    storageBucket: 'sigin-c8c28.appspot.com',
  );
}
